#!/usr/bin/php
<?php

require __DIR__ . '/../common.php';

$repo_dir = getcwd();

list($hook, $ref, $oldsha, $newsha, $oldtreesha, $newtreesha, $access, $refex) = $argv;
$oldsha_s = substr($oldsha, 0, 7);
$newsha_s = substr($newsha, 0, 7);
$branch = end(explode('/', $ref));
$lockfile = getLockFile($repo_dir);

if (file_exists($lockfile) && filemtime($lockfile) > time() - 10 * 60) {
	echo "\033[1;31mWarning: branch `$branch` is already being deployed.\033[0m\n";
	decline($repo_dir);
}
file_put_contents($lockfile, "$oldsha;$newsha");

if ($branch === 'master' || $newsha === '0000000000000000000000000000000000000000') {
	// ignore deploy on master branch and branch deletion
	echo "Pushed $branch $oldsha_s..$newsha_s\n";
	exit(0);
}

$project = getProjectName($repo_dir);

if (!configExists($repo_dir, $newsha)) {
	echo "\033[1;33mWarning: project is not configured for deploy (missing `deploy.json`).\033[0m\n";
	exit(0);
}

$config = readConfig($repo_dir, $newsha);
if (!$config) {
	echo "\033[1;31mCritical: `deploy.json` is not valid json file, aborting push.\033[0m\n";
	decline($repo_dir);
}

$errors = validateConfig($repo_dir, $newsha);
if ($errors) {
	echo "\033[1;31mCritical: `deploy.json` does failed to validate against schema, aborting push:\033[0m\n";
	foreach ($errors as $error) {
		echo "\t\033[1;31m$error\033[0m\n";
	}
	decline($repo_dir);
}

if (!isset($config['targets'][$branch])) {
	echo "\033[1;31mWarning: branch `$branch` is not configured for deploy\n\t(missing key `$branch` under `targets` in `deploy.json`).\033[0m\n";
	exit(0);
}

if (isset($config['pre-update'])) {
	foreach ($config['pre-update'] as $command) {
		//echo "running `$command`\n";
		run("$command", $config['targets'][$branch], function($line) {
			echo $line;
		});
	}
}

// Check if other targets before the current one are not behind
$targets = array_keys($config['targets']);
$toCheck = array_slice($targets, 0, array_search($branch, $targets));
//$toCheck = array_merge(array('master'), $toCheck);

$failed = isCommitIn($repo_dir, $toCheck, $newsha);
if ($failed) {
	$imp = implode(', ', $failed);
	beep(2);
	echo "\033[1;31mWarning: deploy to `$branch` declined - ";
	echo count($failed) === 1 ? "branch $imp is behind." : "branches $imp are behind.";
	echo "\033[0m\n";
	foreach ($failed as $f) {
		echo "\033[34m$f\033[0m ";
		$info = getBranchInfo($repo_dir, $f);
		if ($info) {
			echo "is at \033[34m$info[0]\033[0m\n\t$info[1] $info[2] \033[33m$info[3]\033[0m\n";
		} else {
			echo "has never been deployed\n";
		}
	}
	decline($repo_dir);
}

die(0);
